site_name: "Secrets Cache"
site_url: "http://ritviknag.com/secrets-cache/"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
markdown_extensions:
  - admonition      # enables [!TIP], [!NOTE], etc.
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  # - Lambda Example: lambda_example.md
  # - Features: features.md
  # - Credits: credits.md

docs_dir: docs

plugins:
  - search
  - include-markdown

